### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maxstefaniv** [Autodesk-Forge/forge-api-dotnet-design.automation#16]
More than an issue it is a question:
I just started exploring all the possibilities of Forge.
I cant figure out how to create a work item for AutoCAD.PlotSheetsetToPDF+prod Activity.
I found only this: https://forge.autodesk.com/en/docs/design-automation/v2/tutorials/convert-dwg-to-pdf/
which is the V2 but it states to use the V3 API.
I can find how to build in C# a WorkItem to get a pdf given an dwg.
Could you please share a sample of that kind of Work Item. Or if there is some kind of repository that explains what work item shape is expected for each preconfigured Activities.

Thank you in advance.

**Comment by MadhukarMoogala** [comment]
@maxstefaniv  - Please go through this sample  https://github.com/MadhukarMoogala/FDA_PlotToPdf_v3
