### ISSUE TITLE
TokenCache / Concurrent operations not supported

### ISSUE THREAD

**Issue by DaRochaRomain** [Autodesk-Forge/forge-api-dotnet-design.automation#3]
I've encountered an issue using this API. It seems that TokenCache, which seems to be a dictionnary, can't handle concurrent access done by simultaneous API call. ConcurrentDictionarry might be a solution in this case?

This is the stacktrace that I've got : 
```
System.ThrowHelper:0 in ThrowInvalidOperationException_ConcurrentOperationsNotSupported
System.Collections.Generic.Dictionary`2:479 in TryInsert
Autodesk.Forge.Core.TokenCache:32 in Add
Autodesk.Forge.Core.ForgeHandler+<RefreshTokenAsync>d__11:232 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
Autodesk.Forge.Core.ForgeHandler+<SendAsync>d__8:322 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
System.Runtime.CompilerServices.TaskAwaiter`1:11 in GetResult
Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler+<SendAsync>d__2:190 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter:11 in GetResult
System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__62:141 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
Autodesk.Forge.DesignAutomation.Http.WorkItemsApi+<CreateWorkItemsAsync>d__5:400 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
System.Runtime.CompilerServices.TaskAwaiter`1:11 in GetResult
C:\Users\Romain\Documents\GitHub\FINALCAD.Switch\FINALCAD.Switch\BusinessLogic\Services\ForgeService.cs:574:13 in MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo:12 in Throw
System.Runtime.CompilerServices.TaskAwaiter:46 in HandleNonSuccessAndDebuggerNotification
C:\Users\Romain\Documents\GitHub\FINALCAD.Switch\FINALCAD.Switch\BusinessLogic\Services\ForgeCleanService.cs:128:17 in MoveNext
```

**Comment by szilvaa** [comment]
Thank you for your report.

This issue affects the https://github.com/Autodesk-Forge/forge-api-dotnet-core project not this one. Nevertheless, the fix is in the works in that repo and the PR will reference this issue when it is done.

**Comment by DaRochaRomain** [comment]
Thanks for the deployement. But there is a small issue with your versioning. Nuget dependencies are resolved using lower major / minor and highest patch number. Since you're using none but instead -betax, Autodesk.Forge.Core is always at 1.0.0-beta1 as resolved dependency. 

So, there is a high probability that your fixes/changes are never deployed to users.

**Comment by augustogoncalves** [comment]
my current sample project uses `Autodesk.Forge.DesignAutomation` beta2, when I update it to beta3, it also asks to update the `Autodesk.Forge.Core` beta 3, but that's a user action. Hope I'm not missing anything...

![image](https://user-images.githubusercontent.com/4291593/54926210-988bea00-4eee-11e9-90d6-ba0d62e031e1.png)

![image](https://user-images.githubusercontent.com/4291593/54926346-e4d72a00-4eee-11e9-81d9-8789045eb41d.png)

**Comment by DaRochaRomain** [comment]
You did not miss anything, I did.
The only missing thing, is a Autodesk.Forge.DesignAutomation-beta4 package that is set to use Autodesk.Forge.Core-beta4

**Comment by szilvaa** [comment]
@DaRochaRomain You don't need a new `Autodesk.Forge.DesignAutomation` package. This package is configured to depend on `Autodesk.Forge.Core` 1.0.0-beta3 or **later**. 1.0.0-beta4 is later so it will be used.

**Comment by DaRochaRomain** [comment]
![image](https://user-images.githubusercontent.com/6987690/54983227-a99b3080-4fac-11e9-9b96-8b4bf64079dd.png)

It must be an issue on my side.
