### ISSUE TITLE
GetActivityVersionAsync typo

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-api-dotnet-design.automation#30]
Missing the `t` in `Get`:

1. [IActivitiesApi.GeActivityVersionAsync(...)](https://github.com/Autodesk-Forge/forge-api-dotnet-design.automation/blob/main/src/Autodesk.Forge.DesignAutomation/Http/ActivitiesApi.gen.cs#L111)
2. [ActivitiesApiGeActivityVersionAsync (](https://github.com/Autodesk-Forge/forge-api-dotnet-design.automation/blob/main/src/Autodesk.Forge.DesignAutomation/Http/ActivitiesApi.gen.cs#L585)

**Comment by zhuliice** [comment]
it seems to be here for 3 years :)

**Comment by augustogoncalves** [comment]
I would suggest we fix to GetActivityVersion, but maintain GeActivityVersion with a deprecation/warning notice. That should prevent apps from breaking in this major version. On the next major version, we remove GeActivityVersion.

**Comment by zhuliice** [comment]
makes sense! my PR is too **simple** 😸 , I will work on it later

**Comment by zhuliice** [comment]
@augustogoncalves please review the PR: https://github.com/Autodesk-Forge/forge-api-dotnet-design.automation/pull/31

**Comment by zhuliice** [comment]
@augustogoncalves can we close this issue? https://github.com/Autodesk-Forge/forge-api-dotnet-design.automation/pull/31 is merged
