### ISSUE TITLE
Issue: Error in DesignAutomationClient.CreateWorkItemAsync() after SDK Update

### ISSUE THREAD

**Issue by gusmaoEngbim** [Autodesk-Forge/forge-api-dotnet-design.automation#90]
**Description:**

I've been using the `Autodesk.Forge.DesignAutomation` SDK version 5.1.2 to create WorkItems for design automation, and it has been functioning correctly. However, after updating to version 6.0.0, I encountered an error when using `DesignAutomationClient.CreateWorkItemAsync()` with the same code.

**Error Message:**

```
Field not found: 'Autodesk.Forge.Core.ForgeConfiguration.ScopeKey'.
```

**Code Snippet:**

Below is the portion of the code I use to create the WorkItem:

```csharp
private readonly DesignAutomationClient _designAutomationClient;
public async Task<string> CreateWorkItem(string activeBucket, string activityId)
{
    var newWorkitem = new WorkItem
    {
        ActivityId = activityId,
        Arguments = new Dictionary<string, IArgument>
        {
            { "input", new XrefTreeArgument { Url = $"urn:adsk.objects:os.object:{activeBucket}/input", Verb = Verb.Get, Headers = new Dictionary<string, string> { { "Authorization", $"Bearer {_twoLeggedToken}" } } } },
            { "output", new XrefTreeArgument { Url = $"urn:adsk.objects:os.object:{activeBucket}/output", Verb = Verb.Put, Headers = new Dictionary<string, string> { { "Authorization", $"Bearer {_twoLeggedToken}" } } } }
        },
        LimitProcessingTimeSec = 300
    };

    var workitemCreation = await _designAutomationClient.CreateWorkItemAsync(newWorkitem);

    return workitemCreation.Id;
}
```

**Context:**

In this project, I am using dependency injection to create a transient `ForgeService` for handling tokens within another service. Here is the related code:

```csharp
services.AddTransient<ForgeService>(serviceProvider =>
{
    var tokenService = serviceProvider.GetRequiredService<IApsAuthService>();
    string token = tokenService.GetTwoLeggedToken();

    ForgeService newForgeService = ForgeService.CreateDefault();
    newForgeService.Client.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", $"Bearer {token}");

    return newForgeService;
});
```

---

**Am I missing a new required configuration within version 6.0.0?**

**Comment by szilvaa-adsk** [comment]
Can you post the callstack of the exception, please?

**Comment by gusmaoEngbim** [comment]
Sure @szilvaa-adsk :

`   at Autodesk.Forge.DesignAutomation.Http.WorkItemsApi.CreateWorkItemAsync(WorkItem workItem, String scopes, IDictionary2 headers, Boolean throwOnError)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Autodesk.Forge.DesignAutomation.Http.WorkItemsApi.CreateWorkItemAsync(WorkItem workItem, String scopes, IDictionary2 headers, Boolean throwOnError)
   at Autodesk.Forge.DesignAutomation.DesignAutomationClient.CreateWorkItemAsync(WorkItem workItem)
   at ENG.Qts.ServiceAPS.Services.Internal.ApsDaConditioningService.CreateWorkItem() in c:[...]\ApsDaConditioningService.cs:line 93
   at ENG.Qts.ServiceAPS.Services.RevitAddinService.ExportDataHallsFromRevit() in c:[...]\RevitAddinService.cs:line 60`

**Comment by gusmaoEngbim** [comment]
I have an update:

I have been doing some testing, and I believe the error might be related to the dependency on "Autodesk.Forge.Core" because in this project, I have several Autodesk SDKs:

```xml
<ItemGroup>
    <PackageReference Include="Autodesk.Authentication" Version="2.0.0-beta" />
    <PackageReference Include="Autodesk.DataManagement" Version="1.0.0" />
    <PackageReference Include="Autodesk.Forge.DesignAutomation" Version="6.0.0" />
    <PackageReference Include="Autodesk.Oss" Version="1.1.1" />
    <PackageReference Include="IdentityModel" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.36.0" />
</ItemGroup>
```

Apparently, the Autodesk SDKs are referencing different versions of `Autodesk.Forge.Core`. So by adding the dependency directly, as shown below:

```xml
<PackageReference Include="Autodesk.Forge.Core" Version="4.0.1" />
```

This resolved the issue.

**Comment by szilvaa-adsk** [comment]
Thanks! This is a bug. We should update the dependency so that we pull a newer version of this package. We'll fix it shortly.
